TWITTER_CONSUMER_KEY        = ENV['TWITTER_CONSUMER_KEY']
TWITTER_CONSUMER_SECRET     = ENV['TWITTER_CONSUMER_SECRET']
TWITTER_ACCESS_TOKEN        = ENV['TWITTER_ACCESS_TOKEN']
TWITTER_ACCESS_TOKEN_SECRET = ENV['TWITTER_ACCESS_TOKEN_SECRET']

SLACK_TOKEN = ENV['SLACK_TOKEN']

INTERVAL = 15

CONTEST_TODAY = '本日のコンテスト：'
CONTEST_TODAY_NOTHING = '予定はありません'
CONTEST_1HOUR = 'まであと 1時間 を切りました'
CONTEST_ADDED = '予定に追加されました'
CONTEST_ATCODER = 'AtCoder'
CONTEST_CODEFORCES = 'Codeforces'
CONTEST_TOPCODER = 'topcoder'
